Spread sheet bugs
latrujil913/calm-on pull request #23
Opened 2020-11-23 21:22 UTC by GabrielMarquez0852

- Fixed bugs mentioned on the spread sheet. 
- Updated intro screen for 54321 activity

2020-11-24 02:42 UTC, latrujil913 requested changes
Can you add the newly tinted backgrounds for the Picnic Activity

2020-11-24 18:57 UTC, Zoolyn approved these changes

2020-11-24 21:50 UTC, latrujil913 approved these changes
Looks good, thanks for the added changes

2020-11-25 07:52 UTC, jackzhen1996 approved these changes
good stuff

2020-11-25 23:57 UTC, merged