Activities screen
latrujil913/calm-on pull request #3
Opened 2020-10-05 20:48 UTC by GabrielMarquez0852

- Setup Activities screen
- Included filtering and activity navigation

<p align="center">
  <img src="https://user-images.githubusercontent.com/40918786/95129940-a2f88800-0710-11eb-9e6d-2326a4fbc4c6.png" width="30%" height="30%">
  <img src="https://user-images.githubusercontent.com/40918786/95130114-ed7a0480-0710-11eb-9d68-83398965efb8.png" width="30%" height="30%">
</p>

2020-10-06 20:44 UTC, jackzhen1996 approved these changes
looks good!

2020-10-07 17:00 UTC, latrujil913 commented on App.js
> +//import spriteChat from "./src/components/spriteChat";
Can you remove this comment

2020-10-07 17:01 UTC, latrujil913 commented on src/components/Activities.js
> +    })
Is this being used somehow? If not remove it

2020-10-07 17:02 UTC, latrujil913 commented on src/components/homeStack.js
> +//import Newsfeed from './Newsfeed'
Can you remove this comment

2020-10-07 17:03 UTC, latrujil913 commented on src/stylesheets/activitiesStyles.js
> +        //marginLeft: 26,
Remove commented out styles

2020-10-07 17:05 UTC, latrujil913 requested changes
Can you remove some commented out code. Also if you can add some comments at the top of your functions explaining what they are doing. (High level explination)

2020-10-07 19:54 UTC, latrujil913 approved these changes
Good stuff

2020-10-07 19:54 UTC, merged